# -*- coding: utf-8 -*-
"""sesi10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r9KxFJBJCfJ-CsB2PVJRDIvXuOrJ0SSB
"""

pip install streamlit babel

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st
from babel.numbers import format_currency
from IPython.display import display
sns.set(style='dark')

# Baca data dari file Excel
df_totalitas = pd.read_excel('totalitas.xlsx')

# Tampilkan seluruh data
display(df_totalitas)

# Asumsikan kolom 'tahun' sudah ada di dataframe
df_per_tahun = df_totalitas.groupby('2017')['totalitas'].sum().reset_index()

# Tampilkan dataframe yang sudah dikelompokkan
display(df_per_tahun)